# Array Creation

In [2]:
import numpy as np

a = np.eye(3) # eye => 행렬의 대각 성분에 1을 넣어줌(대각행렬 생성)
b = np.eye(3, 4)

c = np.linspace(10, 20, 5)

print(a)
print(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[10. 20. 30. 40. 50.]
